### ISSUE TITLE
技術選定

### ISSUE THREAD

**Issue by takehiromouri** [GIVIN-pick/pickofficial#1]
・技術選定を行う

**Comment by mkazutaka** [comment]
基本的にGCPを使用する

# TODO
- [x] Server環境の選定 => Kubernetesに決定
 - [x] GKE上にKubenetesクラスタを構築する
- [x] Backend環境の選定
 - [ ] 🈁 gRPCを用いてGoServerを構築する 
- [ ] Frontend環境の選定
- [ ] 検索エンジン環境の選定

# 詳細
本番環境にはKubernetesを使う．これによりデプロイの手間等をなるべく減らす
BackendにはGolangを採用する．またフロントとBackendの通信にはBFFを挟む
これにより，カート機能実現のためのSessionの管理やSSRにより高速化を目指す

理想
Front(preact) <==graphQL?==> BFF(Node.js) <==gRPC==> Server(Golang)
